name: PS-VM-Create

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write         # required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1️⃣ Log in with OIDC and prime an Az PowerShell session
    - name: Azure Login (OIDC)
      uses: Azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true        # ← **critical line**

    # 2️⃣ Run your PowerShell script — no Connect-AzAccount needed
    - name: Run create-vm.ps1
      run: |
        ./create-vm.ps1 `
          -RgName 'rg-pwsh-demo' `
          -VmName 'demo-vm-ci' `
          -Location 'westus2'
      shell: pwsh
