name: deploy-vm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RG_NAME:  rg-pwsh-demo
  VM_NAME:  demo-vm-ci
  LOCATION: westus2          # change if you like

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1️⃣  Secure OIDC login
    - name: Azure login
      uses: Azure/login@v2
      with:
        client-id:       ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # 2️⃣  Install Az modules once per runner
    - name: Install Az modules
      shell: pwsh
      run: |
        Install-Module Az.Accounts,Az.Resources,Az.Compute `
                       -Scope CurrentUser -Force -Repository PSGallery

    # 3️⃣  Run deploy script
    - name: Deploy VM
      shell: pwsh
      env:
        VM_ADMIN_PWD: ${{ secrets.VM_ADMIN_PWD }}   # required
        # VM_ADMIN_USER optional (defaults to azureuser)
      run: |
        ./create-vm.ps1 `
          -RgName   $env:RG_NAME `
          -VmName   $env:VM_NAME `
          -Location $env:LOCATION
