name: PS-VM-Create

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1️⃣ OIDC login + pre-authenticated Az PowerShell session
    - name: Azure Login
      uses: Azure/login@v2
      with:
        client-id:      ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id:      ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true     # ← key line

    # 2️⃣ Run your script in the *same* session (Az cmdlets already loaded & logged in)
    - name: Create VM
      run: |
        ./create-vm.ps1 `
          -RgName 'rg-pwsh-demo' `
          -VmName 'demo-vm-ci' `
          -Location 'westus2'
      shell: pwsh
