name: deploy-vm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write          # OIDC token for Az modules
  contents: read

env:
  RG_NAME:  rg-pwsh-demo
  VM_NAME:  demo-vm-ci
  LOCATION: westus2        # change region if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1️⃣  Log in with OIDC **and** prime Az PowerShell
      - name: Azure login (OIDC + Az)
        uses: Azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true   # ← critical for PowerShell

      # 2️⃣  Deploy the VM
      - name: Deploy VM
        shell: pwsh
        env:
          VM_ADMIN_PWD:  ${{ secrets.VM_ADMIN_PWD }}   # required
          VM_ADMIN_USER: ${{ secrets.VM_ADMIN_USER }}  # optional (defaults to azureuser)
        run: |
          ./create-vm.ps1 `
            -RgName   $env:RG_NAME `
            -VmName   $env:VM_NAME `
            -Location $env:LOCATION
