name: simple-ps-az

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write     # for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. OIDC login (no secrets/keys needed beyond the three in repo settings)
    - name: Azure Login
      uses: Azure/login@v2
      with:
        client-id:      ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id:      ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # 2. Run PowerShell inside the Az-enabled container, then auth with the same OIDC token
    - name: Deploy VM with PowerShell
      uses: Azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          #—— authenticate in this container with the federated token ——#
          $token = Get-Content -Raw $env:AZURE_FEDERATED_TOKEN_FILE
          Connect-AzAccount -ServicePrincipal `
                            -TenantId       $env:AZURE_TENANT_ID `
                            -ApplicationId  $env:AZURE_CLIENT_ID `
                            -FederatedToken $token

          #—— run the deployment script ——#
          Import-Module Az.Resources,Az.Compute -ErrorAction Stop
          ./create-vm.ps1 -RgName 'rg-pwsh-demo' -VmName 'demo-vm-ci' -Location 'westus2'
