name: deploy-vm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write   # for OIDC login
  contents: read

env:
  RG_NAME:  rg-pwsh-demo
  VM_NAME:  demo-vm-ci
  LOCATION: westus2      # change region if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure login (OIDC)
      uses: Azure/login@v2
      with:
        client-id:       ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true   # pre-loads Az modules

    - name: Deploy VM
      shell: pwsh
      env:
        VM_ADMIN_PWD: ${{ secrets.VM_ADMIN_PWD }}   # ← add this secret
        # VM_ADMIN_USER is optional (defaults to azureuser)
      run: |
        ./create-vm.ps1 `
          -RgName   $env:RG_NAME `
          -VmName   $env:VM_NAME `
          -Location $env:LOCATION
