name: deploy-vm-azps

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write        # OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1️⃣  OIDC login + fully-loaded Az PowerShell session
    - name: Azure login (OIDC, Az session)
      uses: Azure/login@v2
      with:
        client-id:       ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true    # ← this downloads Az and keeps auth in the same shell

    # 2️⃣  Run the script in that same session — no extra Connect-AzAccount needed
    - name: Run create-vm.ps1
      shell: pwsh
      run: |
        ./create-vm.ps1 -RgName 'rg-pwsh-demo' -VmName 'demo-vm-ci' -Location 'westus2'
